-- Upgrade SQL from Gleez 1.2.0 to 1.3.0
-- Apply this script to an existing Gleez 1.2.0 database
-- Note: This script should only be run once

-- Disable foreign key checks to allow altering columns that participate in foreign key constraints (charset conversion,
-- column type changes)
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Add soft-delete columns
ALTER TABLE {posts} ADD COLUMN deleted INT UNSIGNED NOT NULL DEFAULT '0' AFTER updated;
ALTER TABLE {posts_versions} ADD COLUMN deleted INT UNSIGNED NOT NULL DEFAULT '0' AFTER updated;
ALTER TABLE {users} ADD COLUMN deleted INT UNSIGNED NOT NULL DEFAULT '0' AFTER updated;
ALTER TABLE {roles} ADD COLUMN deleted INT UNSIGNED NOT NULL DEFAULT '0' AFTER special;
ALTER TABLE {tags} ADD COLUMN deleted INT UNSIGNED NOT NULL DEFAULT '0' AFTER count;
ALTER TABLE {terms} ADD COLUMN deleted INT UNSIGNED NOT NULL DEFAULT '0' AFTER scp;

-- 2. Remove hostname and user_id columns from sessions table
ALTER TABLE {sessions} DROP COLUMN hostname;
ALTER TABLE {sessions} DROP COLUMN user_id;

-- 3. Remove 'access profiles' permission from Anonymous role (rid=1)
DELETE FROM {permissions} WHERE rid = 1 AND permission = 'access profiles';

-- 4. Update Font Awesome icon classes (fa- -> fas fa-)
UPDATE {menus} SET image = CONCAT('fas ', image) WHERE image LIKE 'fa-%' AND image NOT LIKE 'fas %';
UPDATE {widgets} SET icon = CONCAT('fas ', icon) WHERE icon LIKE 'fa-%' AND icon NOT LIKE 'fas %';

-- 5. Change timestamp columns to INT UNSIGNED
ALTER TABLE {posts} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts} MODIFY COLUMN updated INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts} MODIFY COLUMN pubdate INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {comments} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {comments} MODIFY COLUMN updated INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {users} MODIFY COLUMN dob INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {users} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {users} MODIFY COLUMN updated INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {users} MODIFY COLUMN access INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {users} MODIFY COLUMN login INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {messages} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {messages} MODIFY COLUMN sent INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_versions} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_versions} MODIFY COLUMN updated INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_versions} MODIFY COLUMN pubdate INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_tags} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {user_tokens} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {user_tokens} MODIFY COLUMN expires INT UNSIGNED NOT NULL;
ALTER TABLE {sitemaps} MODIFY COLUMN lastmod INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {buddies} MODIFY COLUMN date_requested INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {buddies} MODIFY COLUMN date_accepted INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_clients} MODIFY COLUMN created INT UNSIGNED NOT NULL;
ALTER TABLE {oauth_clients} MODIFY COLUMN updated INT UNSIGNED NOT NULL;
ALTER TABLE {oauth_codes} MODIFY COLUMN expires INT UNSIGNED NOT NULL;
ALTER TABLE {oauth_codes} MODIFY COLUMN created INT UNSIGNED NOT NULL;
ALTER TABLE {oauth_tokens} MODIFY COLUMN access_expires INT UNSIGNED NOT NULL;
ALTER TABLE {oauth_tokens} MODIFY COLUMN refresh_expires INT UNSIGNED NOT NULL;
ALTER TABLE {oauth_tokens} MODIFY COLUMN created INT UNSIGNED NOT NULL;
ALTER TABLE {mail_queue} MODIFY COLUMN last_attempt INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {mail_queue} MODIFY COLUMN created INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {mail_queue} MODIFY COLUMN pubdate INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {mail_queue} MODIFY COLUMN sentdate INT UNSIGNED NOT NULL DEFAULT '0';

-- 6. Add UNSIGNED to non-negative integer columns
ALTER TABLE {posts} MODIFY COLUMN promote TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts} MODIFY COLUMN moderate TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts} MODIFY COLUMN sticky TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts} MODIFY COLUMN format TINYINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {posts} MODIFY COLUMN comment TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {comments} MODIFY COLUMN format TINYINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {users} MODIFY COLUMN gender TINYINT UNSIGNED DEFAULT NULL;
ALTER TABLE {users} MODIFY COLUMN status TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {messages} MODIFY COLUMN format TINYINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {menus} MODIFY COLUMN active TINYINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {modules} MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {modules} MODIFY COLUMN active TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {paths} MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {permissions} MODIFY COLUMN rid INT UNSIGNED NOT NULL;
ALTER TABLE {posts_versions} MODIFY COLUMN promote TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_versions} MODIFY COLUMN moderate TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_versions} MODIFY COLUMN sticky TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_versions} MODIFY COLUMN format TINYINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {posts_versions} MODIFY COLUMN comment TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_tags} MODIFY COLUMN author BIGINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {posts_terms} MODIFY COLUMN parent_id BIGINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_terms} MODIFY COLUMN term_order INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {roles} MODIFY COLUMN special TINYINT UNSIGNED DEFAULT '0';
ALTER TABLE {widgets} MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {widgets} MODIFY COLUMN status TINYINT UNSIGNED DEFAULT '0';
ALTER TABLE {widgets} MODIFY COLUMN cache TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {widgets} MODIFY COLUMN visibility TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {widgets} MODIFY COLUMN show_title TINYINT UNSIGNED DEFAULT '1';
ALTER TABLE {widgets} MODIFY COLUMN format TINYINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {sitemaps} MODIFY COLUMN status TINYINT UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE {oauth_clients} MODIFY COLUMN status TINYINT UNSIGNED NOT NULL;
ALTER TABLE {mail_queue} MODIFY COLUMN status TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {mail_queue} MODIFY COLUMN priority TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {mail_queue} MODIFY COLUMN max_attempts TINYINT UNSIGNED NOT NULL DEFAULT '3';
ALTER TABLE {mail_queue} MODIFY COLUMN attempts TINYINT UNSIGNED NOT NULL DEFAULT '0';

-- 7. Convert all tables to utf8mb4 character set
ALTER TABLE {posts} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {tags} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {terms} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {comments} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {users} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {messages} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {config} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {menus} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {modules} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {paths} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {permissions} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {posts_versions} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {posts_tags} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {posts_terms} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {roles} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {roles_users} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {sessions} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {user_tokens} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {widgets} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {identities} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {sitemaps} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {buddies} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {oauth_clients} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {oauth_codes} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {oauth_tokens} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE {mail_queue} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 8. Fix column types and defaults
ALTER TABLE {oauth_clients} MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {oauth_clients} MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_clients} MODIFY COLUMN `created` INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_clients} MODIFY COLUMN `updated` INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_codes} MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {oauth_codes} MODIFY COLUMN `expires` INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_codes} MODIFY COLUMN `created` INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_tokens} MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {oauth_tokens} MODIFY COLUMN `access_expires` INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_tokens} MODIFY COLUMN `refresh_expires` INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {oauth_tokens} MODIFY COLUMN `created` INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {mail_queue} MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {posts_versions} MODIFY COLUMN layout VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE {buddies} MODIFY COLUMN `accepted` TINYINT UNSIGNED NOT NULL DEFAULT '0';

-- 9. Remove redundant indexes
ALTER TABLE {sessions} DROP INDEX `session`;
ALTER TABLE {messages} DROP INDEX `message_id`;

-- 10. Optimize small table IDs from BIGINT to INT
ALTER TABLE {tags} MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {posts_tags} MODIFY COLUMN tag_id INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {terms} MODIFY COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {posts_terms} MODIFY COLUMN term_id INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {posts_terms} MODIFY COLUMN parent_id INT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE {buddies} MODIFY COLUMN `id` INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE {sitemaps} MODIFY COLUMN id INT UNSIGNED NOT NULL DEFAULT '0';

-- 11. Update schema version to 1.3.0
REPLACE INTO {config} (`group_name`, `config_key`, `config_value`) VALUES
('site', 'version', 's:5:"1.3.0";');

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;
